Test: creating task from the form
VBelopolskii/todo_list pull request #4
Opened 2021-04-24 14:58 UTC by VBelopolskii

эта ветка включает в себя правки из todo-4 после ревью

2021-04-24 21:15 UTC, ianikitin requested changes
Давай немного порефакторим и можно вливать.

2021-04-24 21:15 UTC, ianikitin commented on scripts/app.js
> +    if (inputNewTask.value === '') {
value еще можно затриммить `inputNewTask.value.trim()` - это удалит пробелы в начале и в конце строки. Сейчас, я подозреваю, строка '   ' добавится. А потом начнешь какие-то действия делать с ней и приложение упадет)

2021-04-24 21:15 UTC, ianikitin commented on scripts/app.js
> +        evt.preventDefault();
preventDefault используется и в if, и в else. Можно вынести в самое начало функции и вызывать только один раз.

2021-04-24 21:15 UTC, ianikitin commented on scripts/app.js
> +    } else {
if...else можно упростить и сделать читаемее функцию:
Сначала просто проверяем на false statement:
```if (false) { return }```

А потом если все валидно выполняем задуманное. 
Если объяснил плохо - напиши, кину пример.

2021-04-24 21:15 UTC, ianikitin commented on scripts/app.js
> +                name: inputNewTask.value,
Хорошо мы тоже .trim() сделать над строкой.

2021-04-24 21:15 UTC, ianikitin commented on scripts/tasks.js
> +]
Я думаю ты это знаешь и просто в обучающем проекте оставил, но все же напишу: 
- никогда не оставлять закомментированные участки кода/данных в ветке, которая идет в origin. 
- если есть моковые данные, которые используются в процессе разработки - выносить в отдельный .json файл, типа (TASKS_MOCK_DATA.json). Тут мы json не использовали по двум причинам:
 1. Я если честно хз, импортнется ли .json без сборщика (webpack и прочего) :)
 2. Тут мы не совсем моки использовали, а почти реальные данные и учились импортам/экспортам и работе с объектами.

2021-04-24 21:15 UTC, ianikitin commented on scripts/app.js
> +    taskInput.className = task.isChecked ? 'done' : 'undone';
Ооо, а давай классы в константы уберем.

2021-04-24 21:24 UTC, ianikitin commented
Хороший ритм! Добьем 2 оставшиеся задачки (изменение статуса и сохранение задач после перезагрузки страницы) за выходные? :)

2021-04-25 09:04 UTC, VBelopolskii commented on scripts/app.js
> +    } else {
Сделал. Вот и глянешь, понял я, о чем ты или нет)

2021-04-25 09:05 UTC, VBelopolskii commented on scripts/app.js
> +        evt.preventDefault();
исправил

2021-04-25 09:07 UTC, VBelopolskii commented on scripts/tasks.js
> +]
Я это знаю, но оставил не из-за того, что учебный проект, а из-за невнимательности. Забыл, что закомментировал таски. Пока вернул их в код. Когда сделаю хранилку для сохранения вводимых задач, тогда эти моки уберу

2021-04-25 09:11 UTC, VBelopolskii commented
> Хороший ритм! Добьем 2 оставшиеся задачки (изменение статуса и сохранение задач после перезагрузки страницы) за выходные? :)

Не уверен, просто потому, что хочу сегодня больше внимания ребенку уделить. А она подзаболеть решила :(

Но на неделе точно разберусь и сделаю. Мне прямо нравится потихоньку разбираться со всем)

2021-04-25 09:24 UTC, VBelopolskii commented on scripts/app.js
> +    taskInput.className = task.isChecked ? 'done' : 'undone';
я убрал. Но ты глянь, плиз, то ли я сделал, что ты имел в виду

2021-04-25 09:25 UTC, VBelopolskii commented on scripts/app.js
> +    if (inputNewTask.value === '') {
все так, строка с пробелом добавлялась. Сделал, как ты сказал. Теперь не добавляется. И пробелы в начала и в конце везде обрезаю

2021-04-25 09:26 UTC, VBelopolskii commented on scripts/app.js
> +                name: inputNewTask.value,
да, сначала сделал, потом увидел твой коммент)

2021-04-25 11:25 UTC, ianikitin approved these changes

2021-04-25 11:25 UTC, ianikitin commented on scripts/app.js
> +    const uncheckedTaskClass = 'undone';
Сейчас можно в корень app.js вынести, нет смысла каждый раз присваивать, это ведь константы. И объединить: 
```
const TASK_CSS_CLASS = {
  CHECKED: 'checked',
  UNCHECKED: 'unchecked'
}
```

Гипотетически у тебя дальше в приложении может добавиться логика завязанная на эти классы. И чтобы каждый раз их не хардкодить мы делаем "одну точку входа", и если вдруг изменится название селектора - поменять можно только в одном месте и все будет работать. 

На следующей неделе можем созвониться и обсудить все вопросы, которые появились/остались.

2021-04-25 16:34 UTC, VBelopolskii commented on scripts/app.js
> +    const uncheckedTaskClass = 'undone';
вынес. Заодно поменял применение этих классов, они теперь применяются на родительский элемент li, и теперь таски перечеркиваются в зависимости от примененного класса. Осталось разобраться, как  применять эти классы в зависимости от состояния чек-бокса

2021-05-08 11:22 UTC, closed without merging

2021-05-08 11:23 UTC, VBelopolskii commented
This is not working version